/*************/
// create DOM 
/*************/
var strF='<table>';
strF+='	<tr class="input_item">';
strF+='		<td>';
strF+='			總成本金額';
strF+='		</td>';
strF+='		<td>';
strF+='			<input id="totalCost" type="text" name="totalCost" value="750000">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_check">';
strF+='		<td colspan="2" id="totalCost_check">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_item">';
strF+='		<td>';
strF+='			自行出資金額';
strF+='		</td>';
strF+='		<td>';
strF+='			<input id="SelfCost" type="text" name="SelfCost" value="60000">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_check">';
strF+='		<td colspan="2" id="SelfCost_check">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_item">';
strF+='		<td>';
strF+='			補助金額';
strF+='		</td>';
strF+='		<td>';
strF+='			<p id="SubsidyCost">';
strF+='				5';
strF+='			</p>';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_check">';
strF+='		<td colspan="2" id="SubsidyCost_check">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_item">';
strF+='		<td>';
strF+='			殘值';
strF+='		</td>';
strF+='		<td>';
strF+='			<input id="remainder" type="text" name="remainder" value="12000">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_check">';
strF+='		<td colspan="2" id="remainder_check">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_item">';
strF+='		<td>';
strF+='			累計折舊金額';
strF+='		</td>';
strF+='		<td>';
strF+='			<input id="AccumulatedDepreciation" type="text" name="AccumulatedDepreciation"';
strF+='			value="10000">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_check">';
strF+='		<td colspan="2" id="AccumulatedDepreciation_check">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_item">';
strF+='		<td>';
strF+='			每月攤提金額';
strF+='		</td>';
strF+='		<td>';
strF+='			<input id="depreciation" type="text" name="depreciation" value="1000.01">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_check">';
strF+='		<td colspan="2" id="depreciation_check">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_item">';
strF+='		<td>';
strF+='			總攤提次數';
strF+='		</td>';
strF+='		<td>';
strF+='			<input id="totalTimes" type="text" name="totalTimes" value="48">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_check">';
strF+='		<td colspan="2" id="totalTimes_check">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_item">';
strF+='		<td>';
strF+='			已攤提次數';
strF+='		</td>';
strF+='		<td>';
strF+='			<input id="oldTimes" type="text" name="oldTimes" value="20">';
strF+='		</td>';
strF+='	</tr>';
strF+='	<tr class="input_check">';
strF+='		<td colspan="2" id="oldTimes_check">';
strF+='		</td>';
strF+='	</tr>';
strF+='</table>';
strF+='<button type="button" class="btnSize" onclick="ZeroValue()">';
strF+='	清除';
strF+='</button>';
strF+='<button type="button" class="btnSize" onclick="output()">';
strF+='	送出';
strF+='</button>';


document.getElementById("c1").innerHTML = strF;

var strWriteOutput = '<div id="myOutput1"> testStr </div>';
document.getElementById("c2").innerHTML = strWriteOutput;

var strSystemOutput = '<div id="myOutput2"> testStr </div>';
document.getElementById("c3").innerHTML = strSystemOutput;

var strFixaImg = '<img class="img_assets" src="news_comboBox/custom/fixa.jpg">';
document.getElementById("c4").innerHTML = strFixaImg;

